### ISSUE TITLE
Error when running bowline-gen in Ruby 1.9.2 => rb_add_method: unsupported method type (8)

### ISSUE THREAD

**Issue by Soleone** [maccman/bowline#13]
~/workspace/ruby ➜ bowline-gen app bowline-test
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/core_ext/object/try.rb:29: [BUG] rb_add_method: unsupported method type (8)

ruby 1.9.2dev (2009-07-18 trunk 24186) [i386-darwin10.2.0]

-- control frame ----------
c:0035 p:---- s:0117 b:0117 l:000116 d:000116 CFUNC  :alias_method
c:0034 p:0044 s:0112 b:0112 l:000111 d:000111 CLASS  /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/core_ext/object/try.rb:29
c:0033 p:0009 s:0110 b:0110 l:000109 d:000109 TOP    /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/core_ext/object/try.rb:1
c:0032 p:---- s:0108 b:0108 l:000107 d:000107 FINISH
c:0031 p:---- s:0106 b:0106 l:000105 d:000105 CFUNC  :require
c:0030 p:0012 s:0102 b:0102 l:000085 d:000101 BLOCK  /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209
c:0029 p:0005 s:0100 b:0100 l:000090 d:000099 BLOCK  /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195
c:0028 p:0046 s:0098 b:0098 l:000097 d:000097 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:523
c:0027 p:0041 s:0091 b:0091 l:000090 d:000090 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195
c:0026 p:0013 s:0086 b:0086 l:000085 d:000085 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209
c:0025 p:0143 s:0081 b:0081 l:000080 d:000080 TOP    /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/supermodel-0.1.3/lib/supermodel.rb:13
c:0024 p:---- s:0079 b:0079 l:000078 d:000078 FINISH
c:0023 p:---- s:0077 b:0077 l:000076 d:000076 CFUNC  :require
c:0022 p:0012 s:0073 b:0073 l:000056 d:000072 BLOCK  /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209
c:0021 p:0005 s:0071 b:0071 l:000061 d:000070 BLOCK  /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195
c:0020 p:0046 s:0069 b:0069 l:000068 d:000068 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:523
c:0019 p:0041 s:0062 b:0062 l:000061 d:000061 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195
c:0018 p:0013 s:0057 b:0057 l:000056 d:000056 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209
c:0017 p:0011 s:0052 b:0052 l:000051 d:000051 TOP    /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/lib/bowline/app_config.rb:1
c:0016 p:---- s:0050 b:0050 l:000049 d:000049 FINISH
c:0015 p:---- s:0048 b:0048 l:000047 d:000047 CFUNC  :require
c:0014 p:0012 s:0044 b:0044 l:000027 d:000043 BLOCK  /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209
c:0013 p:0005 s:0042 b:0042 l:000032 d:000041 BLOCK  /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195
c:0012 p:0046 s:0040 b:0040 l:000039 d:000039 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:523
c:0011 p:0041 s:0033 b:0033 l:000032 d:000032 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195
c:0010 p:0013 s:0028 b:0028 l:000027 d:000027 METHOD /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209
c:0009 p:0471 s:0023 b:0023 l:000022 d:000022 TOP    /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/lib/bowline.rb:55
c:0008 p:---- s:0021 b:0021 l:000020 d:000020 FINISH
c:0007 p:---- s:0019 b:0019 l:000018 d:000018 CFUNC  :require
c:0006 p:0043 s:0015 b:0015 l:000014 d:000014 TOP    /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/bin/bowline-gen:3
c:0005 p:---- s:0013 b:0013 l:000012 d:000012 FINISH
c:0004 p:---- s:0011 b:0011 l:000010 d:000010 CFUNC  :load
c:0003 p:0127 s:0007 b:0007 l:002358 d:0022b0 EVAL   /Users/soleone/.rvm/gems/ruby-1.9.2-preview1/bin/bowline-gen:19
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
## c:0001 p:0000 s:0002 b:0002 l:002358 d:002358 TOP   

/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/bin/bowline-gen:19:in `<main>'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/bin/bowline-gen:19:in`load'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/bin/bowline-gen:3:in `<top (required)>'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/bin/bowline-gen:3:in`require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/lib/bowline.rb:55:in `<top (required)>'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in`require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195:in `load_dependency'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:523:in`new_constants_in'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195:in `block in load_dependency'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in`block in require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in `require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/bowline-0.9.3/lib/bowline/app_config.rb:1:in`<top (required)>'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in `require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195:in`load_dependency'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:523:in `new_constants_in'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195:in`block in load_dependency'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in `block in require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in`require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/supermodel-0.1.3/lib/supermodel.rb:13:in `<top (required)>'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in`require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195:in `load_dependency'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:523:in`new_constants_in'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:195:in `block in load_dependency'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in`block in require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/dependencies.rb:209:in `require'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/core_ext/object/try.rb:1:in`<top (required)>'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/core_ext/object/try.rb:29:in `<class:Object>'
/Users/soleone/.rvm/gems/ruby-1.9.2-preview1/gems/activesupport-3.0.0.beta2/lib/active_support/core_ext/object/try.rb:29:in`alias_method'

-- C level backtrace information -------------------------------------------
0   ruby                                0x000000010015d113 rb_vm_bugreport + 195
1   ruby                                0x00000001000340d4 report_bug + 372
2   ruby                                0x0000000100034298 rb_bug + 200
3   ruby                                0x0000000100155e6f rb_alias + 319
4   ruby                                0x00000001001560ab rb_mod_alias_method + 59
5   ruby                                0x0000000100145512 vm_call_cfunc + 354
6   ruby                                0x000000010015a204 vm_call_method + 1268
7   ruby                                0x000000010014aa64 vm_exec_core + 4452
8   ruby                                0x000000010015198e vm_exec + 1102
9   ruby                                0x0000000100151d52 rb_iseq_eval + 306
10  ruby                                0x000000010003a5f8 rb_load_internal + 296
11  ruby                                0x000000010003b8cc rb_require_safe + 1052
12  ruby                                0x0000000100145512 vm_call_cfunc + 354
13  ruby                                0x000000010015a204 vm_call_method + 1268
14  ruby                                0x000000010014e871 vm_exec_core + 20337
15  ruby                                0x000000010015198e vm_exec + 1102
16  ruby                                0x0000000100151d52 rb_iseq_eval + 306
17  ruby                                0x000000010003a5f8 rb_load_internal + 296
18  ruby                                0x000000010003b8cc rb_require_safe + 1052
19  ruby                                0x0000000100145512 vm_call_cfunc + 354
20  ruby                                0x000000010015a204 vm_call_method + 1268
21  ruby                                0x000000010014e871 vm_exec_core + 20337
22  ruby                                0x000000010015198e vm_exec + 1102
23  ruby                                0x0000000100151d52 rb_iseq_eval + 306
24  ruby                                0x000000010003a5f8 rb_load_internal + 296
25  ruby                                0x000000010003b8cc rb_require_safe + 1052
26  ruby                                0x0000000100145512 vm_call_cfunc + 354
27  ruby                                0x000000010015a204 vm_call_method + 1268
28  ruby                                0x000000010014e871 vm_exec_core + 20337
29  ruby                                0x000000010015198e vm_exec + 1102
30  ruby                                0x0000000100151d52 rb_iseq_eval + 306
31  ruby                                0x000000010003a5f8 rb_load_internal + 296
32  ruby                                0x000000010003b8cc rb_require_safe + 1052
33  ruby                                0x0000000100145512 vm_call_cfunc + 354
34  ruby                                0x000000010015a204 vm_call_method + 1268
35  ruby                                0x000000010014aa64 vm_exec_core + 4452
36  ruby                                0x000000010015198e vm_exec + 1102
37  ruby                                0x0000000100151d52 rb_iseq_eval + 306
38  ruby                                0x000000010003a5f8 rb_load_internal + 296
39  ruby                                0x000000010003b2ba rb_f_load + 106
40  ruby                                0x0000000100145512 vm_call_cfunc + 354
41  ruby                                0x000000010015a204 vm_call_method + 1268
42  ruby                                0x000000010014aa64 vm_exec_core + 4452
43  ruby                                0x000000010015198e vm_exec + 1102
44  ruby                                0x0000000100151bf0 rb_iseq_eval_main + 464
45  ruby                                0x0000000100037ba2 ruby_exec_node + 178
46  ruby                                0x0000000100039a24 ruby_run_node + 84
47  ruby                                0x000000010000148f main + 79
48  ruby                                0x0000000100001434 start + 52

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap

**Comment by maccman** [comment]
Sorry, I can't reproduce it. Can you give me some more information about your environment?

**Comment by pushcx** [comment]
From some poking around online, it looks like this is due to a bug in development versions of 1.9.2 and fixed by the time of the full release.
http://redmine.ruby-lang.org/issues/show/1928
