### ISSUE TITLE
script/run fails

### ISSUE THREAD

**Issue by lucasamorimca** [maccman/bowline#20]
lucas@allan:~/hello$ script/run 
script/run:2:in `require': no such file to load -- script/../config/boot (LoadError)
    from script/run:2:in`<main>'

**Comment by fasta** [comment]
I had the same problem. It seems **FILE** does not refer to an absolute path, but when changing the require statement in the script/\* files to the following:

```
require File.join(File.dirname(File.expand_path(__FILE__)), *%w[.. config boot])
```

the Error disappears.

**Comment by turboladen** [comment]
script/run is failing for me as well, but for a different reason.

<pre>
[sloveless@sloveless-mbp:helloworld]$ ./script/run
Setting up Bowline. This could take a while...
/Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:113:in `set_autoload_paths': undefined method `load_paths=' for ActiveSupport::Dependencies:Module (NoMethodError)
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:335:in `process'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in `run'
        from /Users/sloveless/Downloads/helloworld/config/environment.rb:4:in `<top (required)>'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `block in require'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `block in load_dependency'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:570:in `new_constants_in'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `load_dependency'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/tasks/misc.rake:2:in `block in <top (required)>'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:636:in `call'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:631:in `each'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
        from /Users/sloveless/.rvm/rubies/ruby-1.9.1-p378/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:607:in `block in invoke_prerequisites'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:604:in `each'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:596:in `block in invoke_with_call_chain'
        from /Users/sloveless/.rvm/rubies/ruby-1.9.1-p378/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
        from /Users/sloveless/.rvm/gems/ruby-1.9.1-p378/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/commands/run.rb:4:in `<top (required)>'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `block in require'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `block in load_dependency'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:570:in `new_constants_in'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:205:in `load_dependency'
        from /Users/sloveless/Downloads/helloworld/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0.rc/lib/active_support/dependencies.rb:219:in `require'
        from ./script/run:3:in `<main>'
</pre>

**Comment by fasta** [comment]
Well, I also had this error and fixed it for now by using the beta3 of activesupport 3 in my bowline app. (Looks like this in the Gemfile)

```
gem 'activesupport', '3.0.0.beta3'
```

**Comment by pushcx** [comment]
This was fixed in 6a0728
