### ISSUE TITLE
 no such file to load -- vendor/gems/ruby/1.9.1/environment (LoadError)

### ISSUE THREAD

**Issue by cedricdekimpe** [maccman/bowline#21]
I tried to install Bowline using the doc, but when in script/run, here's the error i got : 

script/run 
Setting up Bowline. This could take a while...
/usr/local/lib/ruby/gems/1.8/gems/bowline-0.9.3/lib/bowline/initializer.rb:113:in `set_autoload_paths': undefined method`load_paths=' for ActiveSupport::Dependencies:Module (NoMethodError)
    from /usr/local/lib/ruby/gems/1.8/gems/bowline-0.9.3/lib/bowline/initializer.rb:335:in `process'
    from /usr/local/lib/ruby/gems/1.8/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in`send'
    from /usr/local/lib/ruby/gems/1.8/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in `run'
    from /home/cedric/Documents/Projects/plazyo-desktop/config/environment.rb:4
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:239:in`require'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:239:in`require'
    from /usr/local/lib/ruby/gems/1.8/gems/bowline-0.9.3/lib/bowline/tasks/misc.rake:2
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
    from /usr/local/lib/ruby/1.8/monitor.rb:242:in`synchronize'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in`invoke_prerequisites'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`invoke_prerequisites'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
    from /usr/local/lib/ruby/1.8/monitor.rb:242:in`synchronize'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
    from /usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
    from /usr/local/lib/ruby/gems/1.8/gems/bowline-0.9.3/lib/bowline/commands/run.rb:4
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:239:in `require'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:591:in `new_constants_in'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /usr/local/lib/ruby/gems/1.8/gems/activesupport-3.0.0.rc2/lib/active_support/dependencies.rb:239:in `require'
    from script/run:3

Any help will be appreciated, thanks

Cédric.

PS : I run under Ubuntu Linux with Ruby 1.8.7 (2009-12-24 patchlevel 248) [i686-linux], MBARI 0x8770, Ruby Enterprise Edition 2010.01

**Comment by pushcx** [comment]
This was fixed in 107383c6c375d61035ce139fd9f30f311d68f660
