### ISSUE TITLE
script did not work

### ISSUE THREAD

**Issue by os-hybrid** [maccman/bowline#22]
localhost:helloword Brad$ ./script/run
/Users/Brad/helloword/vendor/gems/ruby/1.9.1/environment.rb:6: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
Setting up Bowline. This could take a while...
/Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:113:in `set_autoload_paths': undefined method`load_paths=' for ActiveSupport::Dependencies:Module (NoMethodError)
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:335:in `process'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/initializer.rb:71:in`run'
    from /Users/Brad/helloword/config/environment.rb:4:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`block in require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/tasks/misc.rake:2:in `block in <top (required)>'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:634:in`call'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:629:in`each'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:629:in `execute'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:595:in`block in invoke_with_call_chain'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:588:in`invoke_with_call_chain'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:605:in `block in invoke_prerequisites'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:602:in`each'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:602:in `invoke_prerequisites'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:594:in`block in invoke_with_call_chain'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:588:in`invoke_with_call_chain'
    from /Users/Brad/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rake.rb:581:in `invoke'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/bowline-0.9.3/lib/bowline/commands/run.rb:4:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `block in require'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in`block in load_dependency'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:591:in `new_constants_in'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in`load_dependency'
    from /Users/Brad/helloword/vendor/gems/ruby/1.9.1/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
    from ./script/run:3:in`<main>'
localhost:helloword Brad$

**Comment by os-hybrid** [comment]
Tried the changes mentioned above but no go.

**Comment by os-hybrid** [comment]
Above being the work arounds mentioned in other posts like it.  How do I find out what build I have of the gem... I am using gem 0.9.3
