### ISSUE TITLE
undefined method `version_requirements' for class `Bundler::Dependency' when bowline-bundle

### ISSUE THREAD

**Issue by giteye-com** [maccman/bowline#32]
```
  caojinhua:.ssh caojinhua$ rvm list

  rvm rubies

     jruby-1.6.4 [ darwin-x86_64-java ]
  => ruby-1.9.2-p180 [ x86_64 ]

  caojinhua:.ssh caojinhua$ gem install bowline
  Fetching: extlib-0.9.15.gem (100%)
  Fetching: templater-1.0.0.gem (100%)
  Fetching: rubyzip2-2.0.1.gem (100%)
  Fetching: supermodel-0.1.6.gem (100%)
  Fetching: bowline-bundler-0.0.4.gem (100%)
  Fetching: bowline-0.9.4.gem (100%)
      **************************************************

        Thank you for installing Bowline.

        If you're on Linux, please install the WebKit library:
          sudo apt-get install libwebkit-dev

      **************************************************
  Successfully installed extlib-0.9.15
  Successfully installed templater-1.0.0
  Successfully installed rubyzip2-2.0.1
  Successfully installed supermodel-0.1.6
  Successfully installed bowline-bundler-0.0.4
  Successfully installed bowline-0.9.4
  6 gems installed
  Installing ri documentation for extlib-0.9.15...
  Installing ri documentation for templater-1.0.0...
  Installing ri documentation for rubyzip2-2.0.1...
  Installing ri documentation for supermodel-0.1.6...
  Installing ri documentation for bowline-bundler-0.0.4...
  Installing ri documentation for bowline-0.9.4...
  Installing RDoc documentation for extlib-0.9.15...
  Installing RDoc documentation for templater-1.0.0...
  Installing RDoc documentation for rubyzip2-2.0.1...
  Installing RDoc documentation for supermodel-0.1.6...
  Installing RDoc documentation for bowline-bundler-0.0.4...
  Installing RDoc documentation for bowline-0.9.4...
  caojinhua:.ssh caojinhua$ bowline-gen app helloworld
  Generating with app generator:
       [ADDED]  vendor
       [ADDED]  lib
       [ADDED]  db
       [ADDED]  build
       [ADDED]  log
       [ADDED]  public
       [ADDED]  app
       [ADDED]  app/models
       [ADDED]  app/binders
       [ADDED]  app/helpers
       [ADDED]  app/windows
       [ADDED]  config
       [ADDED]  config/initializers
       [ADDED]  config/first_run
       [ADDED]  app_first_run
       [ADDED]  Rakefile
       [ADDED]  Gemfile
       [ADDED]  public/index.html
       [ADDED]  public/javascripts/application.js
       [ADDED]  public/stylesheets/application.css
       [ADDED]  script/build
       [ADDED]  script/console
       [ADDED]  script/generate
       [ADDED]  script/init
       [ADDED]  script/run
       [ADDED]  config/environment.rb
       [ADDED]  config/environments/development.rb
       [ADDED]  config/environments/production.rb
       [ADDED]  .gitignore
       [ADDED]  public/icon.png
       [ADDED]  script
       [ADDED]  public/javascripts/jquery.js
       [ADDED]  public/javascripts/jquery.chain.js
       [ADDED]  public/javascripts/superclass.js
       [ADDED]  public/javascripts/bowline.js
       [ADDED]  public/javascripts/bowline.chain.js
       [ADDED]  app/windows/main_window.rb
       [ADDED]  config/application.yml
       [ADDED]  config/database.yml
       [ADDED]  config/boot.rb
       [ADDED]  README
  caojinhua:.ssh caojinhua$ cd 
  github_rsa                 github_rsa.pub_bak-github  helloworld/                id_rsa.pub
  github_rsa.pub             github_rsa_bak-github      id_rsa                     known_hosts
  caojinhua:.ssh caojinhua$ cd helloworld/
  caojinhua:helloworld caojinhua$ bowline-bundle 
  /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:59:in `<class:Dependency>': undefined method `version_requirements' for class `Bundler::Dependency' (NameError)
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:4:in `<module:Bundler>'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:1:in `<top (required)>'
    from /Users/caojinhua/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/caojinhua/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bowline-bundler-0.0.4/lib/bowline/bundler.rb:18:in `<top (required)>'
    from /Users/caojinhua/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/caojinhua/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bowline-bundler-0.0.4/bin/bowline-bundle:4:in `<top (required)>'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/bin/bowline-bundle:19:in `load'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/bin/bowline-bundle:19:in `<main>'
  caojinhua:helloworld caojinhua$
```

**Comment by schiza** [comment]
same here..

```
$ rvm list

rvm rubies

=> ruby-1.9.2-p290 [ i386 ]
```

**Comment by garnieretienne** [comment]
```
kurt@adam:~/tmp/bowline/helloworld$ bowline-bundle install
/home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:59:in `<class:Dependency>': undefined method `version_requirements' for class `Bundler::Dependency' (NameError)
    from /home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:4:in `<module:Bundler>'
    from /home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:1:in `<top (required)>'
    from /home/kurt/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kurt/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing/gems/bowline-bundler-0.0.4/lib/bowline/bundler.rb:18:in `<top (required)>'
    from /home/kurt/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kurt/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing/gems/bowline-bundler-0.0.4/bin/bowline-bundle:4:in `<top (required)>'
    from /home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing/bin/bowline-bundle:19:in `load'
    from /home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing/bin/bowline-bundle:19:in `<main>'

```

Same here !

```
kurt@adam:~/tmp/bowline/helloworld$ gem list

*** LOCAL GEMS ***

activemodel (3.1.1.rc2, 3.0.10)
activesupport (3.1.1.rc2, 3.0.10)
bowline (0.9.4)
bowline-bundler (0.0.4)
builder (3.0.0, 2.1.2)
bundler (1.0.15)
diff-lcs (1.1.3)
extlib (0.9.15)
highline (1.6.2)
i18n (0.6.0, 0.5.0)
multi_json (1.0.3)
rake (0.8.7)
rubyzip2 (2.0.1)
supermodel (0.1.6, 0.1.4)
templater (1.0.0)
tzinfo (0.3.30)
```

```
kurt@adam:~/tmp/bowline/helloworld$ rvm info

ruby-1.9.2-p290@bowline-testing:

  system:
    uname:       "Linux adam 2.6.35-30-generic #59-Ubuntu SMP Tue Aug 30 19:00:03 UTC 2011 x86_64 GNU/Linux"
    bash:        "/bin/bash => GNU bash, version 4.1.5(1)-release (x86_64-pc-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.6.31 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]"

  ruby:
    interpreter:  "ruby"
    version:      "1.9.2p290"
    date:         "2011-07-09"
    platform:     "x86_64-linux"
    patchlevel:   "2011-07-09 revision 32553"
    full_version: "ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]"

  homes:
    gem:          "/home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing"
    ruby:         "/home/kurt/.rvm/rubies/ruby-1.9.2-p290"

  binaries:
    ruby:         "/home/kurt/.rvm/rubies/ruby-1.9.2-p290/bin/ruby"
    irb:          "/home/kurt/.rvm/rubies/ruby-1.9.2-p290/bin/irb"
    gem:          "/home/kurt/.rvm/rubies/ruby-1.9.2-p290/bin/gem"
    rake:         "/home/kurt/.rvm/gems/ruby-1.9.2-p290@global/bin/rake"

  environment:
    PATH:         "/home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing/bin:/home/kurt/.rvm/gems/ruby-1.9.2-p290@global/bin:/home/kurt/.rvm/rubies/ruby-1.9.2-p290/bin:/home/kurt/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
    GEM_HOME:     "/home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing"
    GEM_PATH:     "/home/kurt/.rvm/gems/ruby-1.9.2-p290@bowline-testing:/home/kurt/.rvm/gems/ruby-1.9.2-p290@global"
    MY_RUBY_HOME: "/home/kurt/.rvm/rubies/ruby-1.9.2-p290"
    IRBRC:        "/home/kurt/.rvm/rubies/ruby-1.9.2-p290/.irbrc"
    RUBYOPT:      ""
    gemset:       "bowline-testing"
```

64 bits effect ?

**Comment by swistak** [comment]
ditto.

Btw why specialized bundler at all?

**Comment by greyblake** [comment]
Same.

**Comment by garcy** [comment]
same, only difference is ruby-1.9.2-p180

**Comment by railsdev** [comment]
anyone have fixed this issue????

**Comment by swistak** [comment]
no. And it looks like project is abandoned. It's not trivial, I tried to take a stab at it, but tons for dependencies are outdated, and i think project simply requires rewrite. Striping core and using modern version of library dependencies.

**Comment by railsdev** [comment]
yeah... i agree with you swistak... I was trying hard to make it work...
