### ISSUE TITLE
Unable to run example app

### ISSUE THREAD

**Issue by corvallo** [maccman/bowline#34]
I've installed by rvm ruby and then by gem bowline

when i try to do the 4th step of the example app ( the command bowline-bundle)
I get this:
corvallo@XPS-L501X:~/bowline/helloworld$ bowline-bundle 
/home/corvallo/.rvm/gems/ruby-1.9.2-p290/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:59:in `<class:Dependency>': undefined method`version_requirements' for class `Bundler::Dependency' (NameError)
    from /home/corvallo/.rvm/gems/ruby-1.9.2-p290/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:4:in`module:Bundler'
    from /home/corvallo/.rvm/gems/ruby-1.9.2-p290/gems/bowline-bundler-0.0.4/lib/bowline/bundler/dependency.rb:1:in `<top (required)>'
    from /home/corvallo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /home/corvallo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/corvallo/.rvm/gems/ruby-1.9.2-p290/gems/bowline-bundler-0.0.4/lib/bowline/bundler.rb:18:in`<top (required)>'
    from /home/corvallo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/corvallo/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /home/corvallo/.rvm/gems/ruby-1.9.2-p290/gems/bowline-bundler-0.0.4/bin/bowline-bundle:4:in `<top (required)>'
    from /home/corvallo/.rvm/gems/ruby-1.9.2-p290/bin/bowline-bundle:19:in`load'
    from /home/corvallo/.rvm/gems/ruby-1.9.2-p290/bin/bowline-bundle:19:in `<main>'
How can I solve this
thx in advance

**Comment by ghost** [comment]
i guess bundler is newer than the used bundler version for the latest release. in 1 year bundler has developed further while bowline sadly has not.

**Comment by corvallo** [comment]
So there's a way to solve this issue, i've to install a previous version of bowline bundler?

**Comment by davidslvto** [comment]
there is no new version of this.

The project was great, but it seems abandoned.... shame

**Comment by ghost** [comment]
indeed it is.

but there are alternatives around.
https://github.com/phonegap/phonegap

or the fork of phonegap
https://github.com/maccman/macgap

**Comment by wgf4413** [comment]
bowline-bundle install
我同样出现了这个错误，不知道什么解决，寻求帮助

**Comment by lance-ding** [comment]
请问楼上的解决了吗？

**Comment by JoeWoo** [comment]
貌似是version问题，搞不定。waiting for bowline-team fixes it
